#!/bin/bash

export BOARD=$1

mkdir -p /opt/BUILD/${BOARD}

cd /opt/iotkitv3
for PRG in $(find [a-z]* -mindepth 1 -maxdepth 1 -type d | grep -v images)
do
    cd /opt/template
    mbed compile -m ${BOARD} --source . --source ../iotkitv3/${PRG}

    N=$(echo ${PRG} | tr '/' '_')
    mv -v BUILD/${BOARD}/GCC_ARM/template.bin ../BUILD/${BOARD}/${N}.bin
done
