#!/bin/bash
#
#	Compiliert mbed Programme im Container mit vor compilierten Libraries.
#
#	Aufruf: compile [Path relativ zu /src]

if	[ $# -gt 0 ]
then
	export SRC=/src/$1
	shift
else
	export SRC=$(pwd)
fi

export OUT=${SRC}/BUILD

cd /opt/template
rm -rf ${OUT}
mbed compile --source ${SRC} --source . --build ${OUT} $*
