#!/bin/bash
#
#       Compiliert mbed Programme im Container mit vor compilierten Libraries.
#
#       Aufruf: compile [Path relativ zu /src]

if      [ $# -gt 0 ] && [ "$1" != "-m" ]
then
        export SRC=/src/$1
        shift
else
        export SRC=$(pwd)
fi

export OUT=/src/$(basename ${SRC})

cd /opt/template
mbed compile --source ${SRC} --source . -N ${OUT} $*
