apiVersion: v1
kind: Service
metadata:
  name: nexus3
  labels:
    app: nexus3
    group: system
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    nodePort: 32511   
    protocol: TCP
    name: nexus3
  - port: 8082
    nodePort: 32512   
    protocol: TCP  
    name: docker-group 
  - port: 8083
    nodePort: 32513   
    protocol: TCP  
    name: docker-proxy    
  selector:
    app: nexus3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
        tier: backend
    spec:
      containers:
      - name: nexus3
        image: sonatype/nexus3
        ports:
        - containerPort: 8081
          name: nexus3
        - containerPort: 8082
          name: docker-group          
        - containerPort: 8083
          name: docker-proxy          