# GitPod Configuration
image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
      . ${GITPOD_REPO_ROOT}/scripts/init.sh  
      touch "$AWS_CONFIG_FILE"
      echo "$K8S_CONFIG" | base64 -d > ~/.kube/config      
      curl https://raw.githubusercontent.com/mc-b/lerncloud/main/ssh/lerncloud -o ~/.ssh/id_rsa
      chmod 0600 ~/.ssh/id_rsa

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
  
# Jupyter Notebooks Port intern  
ports:
  - port: 9000-9100
    onOpen: ignore  
    
