apiVersion: v1
kind: Service
metadata:
  name: apache-rest
  labels:
    app: apache-rest
    group: iot
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-rest
  template:
    metadata:
      labels:
        app: apache-rest
        group: iot
        tier: frontend
    spec:
      containers:
      - name: apache-rest
        image: marcel1691/apache-rest
        ports:
        - containerPort: 80
        stdin: true 
        tty: true         

          