apiVersion: v1
kind: Service
metadata:
  name: fhem-port
  labels:
    app: fhem-port
    group: iot
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: fhem-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhem-port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhem-port
  template:
    metadata:
      labels:
        app: fhem-port
        group: iot
        tier: frontend
    spec:
      containers:
      - name: fhem-port
        image: marcel1691/fhem
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
