apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    group: iot
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
  selector:
    app: mosquitto
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        group: iot
        tier: backend
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        stdin: true 
        tty: true         

          