apiVersion: v1
kind: Service
metadata:
  name: openhab
  labels:
    app: openhab
    group: iot
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: openhab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
        group: iot
        tier: frontend
    spec:
      containers:
      - name: openhab
        image: openhab/openhab
        ports:
        - containerPort: 8080
        stdin: true 
        tty: true         

          