apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jupyter-base
  labels:
    app: jupyter-base
spec:
  selector:
    matchLabels:
      app: jupyter-base
  endpoints:
  - port: jupyter-base
    interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-frontend
  labels:
    prometheus: frontend
spec:
  serviceMonitors:
  - selector:
      matchLabels:
        app: jupyter-base