apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
    tier: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec:
      containers:
      - image: mongo
        name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: test
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        ports:
        - containerPort: 27017
          name: mongodb
