apiVersion: v1
kind: Service
metadata:
  name: beakerx
  labels:
    app: beakerx
    group: web
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    nodePort: 32088    
    protocol: TCP
  selector:
    app: beakerx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beakerx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beakerx
  template:
    metadata:
      labels:
        app: beakerx
        group: web
        tier: frontend
    spec:
      containers:
      - name: beakerx
        image: beakerx/beakerx
        imagePullPolicy: IfNotPresent
        command: [ "start-notebook.sh", "--NotebookApp.token=''" ]        
        ports:
        - containerPort: 8888
          name: beakerx
        # Volumes im Container
        volumeMounts:
        - mountPath: "/home/beakerx/work"
          subPath: beakerx
          name: "beakerx-data"
      # Volumes in Host
      volumes:
      - name: "beakerx-data"
        persistentVolumeClaim:
         claimName: data-claim   
                              