apiVersion: v1
kind: Service
metadata:
  name: dind
  labels:
    app: dind
    group: docker
    tier: backend
spec:
  ports:
  - port: 2375
    protocol: TCP
  selector:
    app: dind
  clusterIP: None     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
        group: docker
        tier: backend
    spec:
      containers:
      - name: dind
        image: registry.gitlab.com/mc-b/misegr/docker/20-dind
        imagePullPolicy: IfNotPresent
        command: [ "dockerd" ]
        args: [ "--host=tcp://0.0.0.0:2375" ]
        ports:
        - containerPort: 2375
          name: dind
        securityContext:
         privileged: true          
