apiVersion: v1
kind: Service
metadata:
  name: dind
  labels:
    app: dind
    group: docker
    tier: backend
spec:
  ports:
  - port: 2375
    protocol: TCP
  selector:
    app: dind
  clusterIP: None     
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
        group: docker
        tier: backend
    spec:
      containers:
      - name: dind
        image: docker:stable-dind
        ports:
        - containerPort: 2375
          name: dind
        securityContext:
         privileged: true          
