apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
    group: web
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    nodePort: 32288    
    protocol: TCP
  selector:
    app: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
        group: web
        tier: frontend
    spec:
      containers:
      - name: jupyter
        image: jupyter/tensorflow-notebook
        imagePullPolicy: IfNotPresent
        command: [ "start-notebook.sh", "--NotebookApp.token=''" ]        
        ports:
        - containerPort: 8888
          name: jupyter
        # Volumes im Container
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          subPath: jupyter        
          name: "jupyter-data"
      # Volumes in Host
      volumes:
      - name: "jupyter-data"
        persistentVolumeClaim:
         claimName: data-claim 
                    