apiVersion: v1
kind: Service
metadata:
  name: jupyter-base
  labels:
    app: jupyter-base
    group: web
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    nodePort: 32188    
    protocol: TCP
  selector:
    app: jupyter-base
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-base
  template:
    metadata:
      labels:
        app: jupyter-base
        group: web
        tier: frontend
    spec:
      containers:
      - name: jupyter-base
        image: registry.gitlab.com/mc-b/misegr/base-notebook
        imagePullPolicy: IfNotPresent
        command: [ "start-notebook.sh", "--NotebookApp.token=''" ]        
        ports:
        - containerPort: 8888
          name: jupyter-base
        # Volumes im Container
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          subPath: jupyter        
          name: "jupyter-data"
        env:
        - name: DOCKER_HOST
          value: "tcp://dind:2375" 
      # Volumes in Host
      volumes:
      - name: "jupyter-data"
        persistentVolumeClaim:
         claimName: data-claim  
