apiVersion: v1
kind: Service
metadata:
  name: osticket
  labels:
    app: osticket
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: osticket
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: osticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
        group: customer
        tier: frontend
    spec:
      containers:
      - name: osticket
        image: campbellsoftwaresolutions/osticket
        env:
        - name: MYSQL_HOST
          value: osticket-mysql
        - name: MYSQL_PASSWORD
          value: secret        
        ports:
        - containerPort: 80
          name: osticket
