apiVersion: apps/v1
kind: Deployment
metadata:
  name: make
spec:
  replicas: 1
  selector:
    matchLabels:
      app: make
  template:
    metadata:
      labels:
        app: make
        group: compiler
    spec:
      containers:        
      - name: make
        image: misegr/make
        imagePullPolicy: IfNotPresent        
        # Just spin & wait forever
        command: [ "sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: "/src"
          subPath: src
          name: "host-data"
      volumes:
      - name: "host-data"
        persistentVolumeClaim:
         claimName: data-claim  