apiVersion: v1
kind: ConfigMap
data:
  index: |-
    <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Web Server Version 1</title>
    </head>
    <body>
    <h1>Web Server Version 1</h1>
    Hallo ich bin in einer ConfigMap gespeichert.
    </body>
    </html>
metadata:
  name: web1
