apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
    - port: 7000
  selector:
    app: cassandra
    tier: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra
        tier: db
    spec:
      containers:
      - image: cassandra
        name: cassandra
        ports:
        - containerPort: 7000
          name: cassandra
