apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
    group: iot
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 7474 
    targetPort: 7474 
    protocol: TCP
  selector:
    app: neo4j
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
        group: iot
        tier: frontend
    spec:
      containers:
      - name: neo4j
        image: neo4j:3.0
        ports:
        - containerPort: 7474 
        stdin: true 
        tty: true         

          