apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  labels:
    app: zeppelin
    group: iot
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080 
    targetPort: 8080 
    protocol: TCP
  selector:
    app: zeppelin
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: zeppelin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        app: zeppelin
        group: iot
        tier: frontend
    spec:
      containers:
      - name: zeppelin
        image: aquila/zeppelin
        env:
        - name: ZEPPELIN_SERVER_CONTEXT_PATH
          value: /zeppelin
        - name: ZEPPELIN_MEM
          value: -Xmx2028m -XX:MaxPermSize=512m
        ports:
        - containerPort: 8080 
