apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: adminer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
        group: customer
        tier: frontend
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080
          name: adminer
