apiVersion: batch/v1
kind: Job
metadata:
  name: loaddata
spec:
  parallelism: 1
  template:
   spec:
    containers:
    - name: loaddata
      image: debian:jessie
      imagePullPolicy: IfNotPresent
    restartPolicy: Never
