apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: web-viewer
  namespace: default
spec:
  rules:
  - services: ["web.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-web-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "web-viewer"
