apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    name: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
    tier: middleware
  clusterIP: None    
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: middleware
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        imagePullPolicy: IfNotPresent    
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        ports:
        - containerPort: 9092
          name: kafka
