apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mqtt-kafka-bridge
  labels:
    app: mqtt-kafka-bridge
spec:
  selector:
    matchLabels:
      app: mqtt-kafka-bridge
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqtt-kafka-bridge
        tier: middleware
    spec:
      containers:
      - name: mqtt-kafka-bridge
        image: devicexx/mqtt-kafka-bridge
        imagePullPolicy: IfNotPresent    
        command: [ "java", "-jar", "/opt/mqttKafkaBridge.jar" ]
        args: [ "-b", "kafka:9092", "--uri", "tcp://broker.hivemq.com:1883", "--topics", "iotkit/#" ]