apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-kafka-bridge
  labels:
    app: mqtt-kafka-bridge
spec:
  selector:
    matchLabels:
      app: mqtt-kafka-bridge
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqtt-kafka-bridge
        tier: middleware
    spec:
      containers:
      - name: mqtt-kafka-bridge
        image: devicexx/mqtt-kafka-bridge
        imagePullPolicy: IfNotPresent    
        command: [ "java", "-jar", "/opt/mqttKafkaBridge.jar" ]
        args: [ "-b", "kafka:9092", "--uri", "tcp://iotkit.mc-b.ch:1883", "--topics", "iotkit/#" ]