apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    name: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
    tier: middleware
  clusterIP: None    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
        tier: middleware
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent 
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"           
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"        
        ports:
        - containerPort: 2181
          name: zookeeper