apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
        group: web
        tier: frontend
    spec:
      containers:
      - name: webgoat
        image: webgoat/webgoat-8.0
        env:
        - name: WEBWOLF_HOST
          value: webwolf
        - name: WEBWOLF_PORT
          value: "9090"         
        command: [ "java" ]
        args: [ "-Djava.security.egd=file:/dev/./urandom", "-jar", "/home/webgoat/webgoat.jar", "--server.port=8080", "--server.address=0.0.0.0" ]
        ports:
        - containerPort: 8080
          name: webgoat
