apiVersion: v1
kind: Service
metadata:
  name: webgoat
  labels:
    app: webgoat
    group: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: webgoat