apiVersion: apps/v1
kind: Deployment
metadata:
  name: webwolf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webwolf
  template:
    metadata:
      labels:
        app: webwolf
        group: web
        tier: frontend
    spec:
      containers:
      - name: webwolf
        image: webgoat/webwolf
        command: [ "/bin/bash", "-c" ]      
        args: [ "sleep 8 && java -Djava.security.egd=file:/dev/./urandom -jar /home/webwolf/webwolf.jar",
                " --server.port=9090 --server.address=0.0.0.0 --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat" ] 
        ports:
        - containerPort: 9090
          name: webwolf       